version: '3.7'

services:
  database:
    image: mongo
    restart: always
    volumes:
      - ~/data/db:/data/db
    networks:
      - webapp-network
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - database
    ports:
      - 8181:8181
    networks:
      - webapp-network
networks:
  webapp-network:
    driver: bridge