version: '3.7'

services:
  database:
    image: mongo
    restart: always
    volumes:
      - ~/data/db:/data/db
    networks:
      - webapp-network

  web:
    context: .
    dockerfile: Dockerfile
    image: api_online
    container_name: api_online
    restart: always
    depends_on:
      - database
    ports:
      - 8082:8082
    networks:
      - webapp-network

networks:
  webapp-network:
    driver: bridge